load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "agent",
    srcs = [
        "agent.go",
        "agents.go",
    ],
    embedsrcs = [
        "INSTRUCTION_DESTROYER.md",
        "INSTRUCTION_MODIFIER.md",
        "INSTRUCTION_ORCHESTRATOR.md",
        "INSTRUCTION_RETRIEVAL.md",
    ],
    importpath = "github.com/eat-pray-ai/yutu/cmd/agent",
    visibility = ["//visibility:public"],
    deps = [
        "//cmd",
        "@com_github_modelcontextprotocol_go_sdk//mcp",
        "@com_github_spf13_cobra//:cobra",
        "@org_golang_google_adk_v2//agent",
        "@org_golang_google_adk_v2//agent/llmagent",
        "@org_golang_google_adk_v2//cmd/launcher",
        "@org_golang_google_adk_v2//cmd/launcher/full",
        "@org_golang_google_adk_v2//memory",
        "@org_golang_google_adk_v2//model",
        "@org_golang_google_adk_v2//model/gemini",
        "@org_golang_google_adk_v2//session",
        "@org_golang_google_adk_v2//tool",
        "@org_golang_google_adk_v2//tool/geminitool",
        "@org_golang_google_adk_v2//tool/mcptoolset",
        "@org_golang_google_genai//:genai",
    ],
)
