name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v3
        with:
          repo_token: ${{ github.token }}
          issue_message: "Welcome to yutu, thank you for opening your first issue!"
          pr_message: "Welcome to yutu, thank you for opening your first PR!"
