# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '33 21 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30
          days-before-pr-stale: 60
          days-before-issue-close: 15
          days-before-pr-close: 15
          exempt-all-assignees: true
          stale-issue-message: "Marked as stale since no activity for 30 days, close in 15 days if no activity."
          stale-pr-message: "Marked as stale since no activity for 60 days, close in 15 days if no activity."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
